name: 'Stock Biu Bot'

on:
  schedule:
    - cron: '* * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install node'
        uses: actions/setup-node@v2
      - name: 'Install NPM dependencies'
        run: npm install
      - name: 'Run code'
        run: node biu.js
        env:
          API_KEY: ${{ secrets.ACCESS_TOKEN }}
